### PR TITLE
nos3#226 - 64bit

### PR DESCRIPTION
**Pull request by jlucas9**
Could potentially the ITC Common and NOS Engine packages to suppress warnings. 

Seems to build and run successfully though!

### CODE REVIEW

**Review by Isgaroth-the-Green — APPROVED** [review]
Everything works as far as I can tell, and the code all looks reasonable.

**Review by kevincbruce — APPROVED** [review]
The changes all seem reasonable to me.

**Review by Donnie-Ice — APPROVED** [review]
Looks good!

**Review by msuder — APPROVED** [review]
Changes look ok to me.  Ran tests and they work ok also.

**Review by rjbrown2 — APPROVED** [review]

**Comment by jlucas9** [comment]
Merges to be completed prior to this top level PR:
- [ ] arducam
- [ ] adcs
- [ ] css
- [ ] eps
- [ ] fss
- [ ] imu
- [ ] mag
- [ ] radio
- [ ] reaction wheel
- [ ] star tracker
- [ ] torquer
- [ ] novatel
- [ ] sample
- [ ] osal
- [ ] ci
- [ ] hwlib
- [ ] sch
- [ ] to
- [ ] time driver
- [ ] sim common
- [ ] truth 42 sim

**Pull request merged**
