### PR TITLE
[nasa/nos3#80] YAMCS Integration

### PR DESCRIPTION
**Pull request by jlucas9**
Thanks to @xpromache and @rjbrown2 for getting this going! By default using yamcs moving forward!

Must first merge https://github.com/nasa-itc/yamcs-nos3/pull/1

### CODE REVIEW

**Comment by rjbrown2** [comment]
Tested this locally.  Fixes my issue with Telemetry, and see where the issue happened.  
Good catch and fix.  Working for Studio now.

**Review by rjbrown2 — APPROVED** [review]
Thanks all!

**Comment by rjbrown2** [comment]
Note:  There appears to be an issue within Windows 11, and the NOS Time driver.

Nos Time Driver...
Error response from daemon: No such container: nos_time_driver  

We should investigate and fix for Win11 Systems after the merge.

**Review by kevincbruce — APPROVED** [review]
Tried out a variety of commands from a few apps and looked through TLM, and it all seemed to work, and the links could all open!

**Comment by rjbrown2** [comment]
> Everything appears to work on my side. One small note: there may be an issue with `scripts/cfg/prepare.sh lines 9-10`, doesn't appear to do anything. That was not introduced in this PR though.

Good catch.  Appears to be duplicated code on my side.  I'll add a fix here for the merge.

**Pull request merged**
