### PR TITLE
Release 1.7.1

### PR DESCRIPTION
**Pull request by jlucas9**

### CODE REVIEW

**Comment by jlucas9** [comment]
Confirmed both via shared folders and cloned direct in the provisioned VM:
```
git clone https://github.com/nasa/nos3.git
git checkout dev
git submodule update --init --recurisve
make real-clean
make prep
make
make launch
```

Wait and confirm we get into ADCS mode 2 (sun pointed) and resolve correctly after a minute or two.  
In the COSMOS test runner:
* Test Suite: Mission_Test
* Test Group: LPT 
* START (at test group level)

Confirm test passes and still sun pointed.

**Review by kevincbruce — APPROVED** [review]
Looked through and looks good! I tested the Normal Behavior script on this version (dev branch), with updates to include some thruster commands and for general compatibility, and  it ran through with no issues, which verifies that most or all apps are at least producing commands and telemetry stably over the course of hours. Also confirms successful CFDP, RTS Loads, DS captures with a custom table, rotation, NOOPs, TLM requests, RTS runs, among other actions still work.

**Comment by zlynch2** [comment]
When make real-clean and re-making things work fine. However If I make stop and make launch back to back. Cosmos doesn't seem to launch its Nos3 Launcher after clicking ok. Can others confirm. I know kevin mentioned he noticed this

**Comment by szemerick** [comment]
> When make real-clean and re-making things work fine. However If I make stop and make launch back to back. Cosmos doesn't seem to launch its Nos3 Launcher after clicking ok. Can others confirm. I know kevin mentioned he noticed this

I saw this same behavior yesterday when @msuder demo'ed some stuff to me.  @msuder was probably using the latest dev branch. I think he fixed it by re-building.

**Review by zlynch2 — APPROVED** [review]
Approving seems to work as long as we rebuild after launching. I can try and look into that issue too, it may not be obvious why cosmos doesn't pop up.

**Review by szemerick — APPROVED** [review]
approved. re-created the COSMOS launching issue, which has been filed.

**Review by msuder — APPROVED** [review]
Reviewed and tested pull request code changes.  They all look good to me.

**Pull request merged**
