### PR TITLE
Release Candidate 1.7.0

### PR DESCRIPTION
**Pull request by jlucas9**

### CODE REVIEW

**Review by rjbrown2 — APPROVED** [review]
Whew, that was a lot to go through.

**Review by Isgaroth-the-Green — APPROVED** [review]
Everything seems to run, as long as it is using the most recent COSMOS (is that pointed to in this release candidate? I created a new clone and, when cloning the submodules, it did not get the most recent version).

**Review by Donnie-Ice — APPROVED** [review]
Lotta files, all looks good though!

**Comment by szemerick** [comment]
Tried out the release candidate. Looks good.  Release!

**Review by szemerick — APPROVED** [review]
Approved!

**Review by zlynch2 — APPROVED** [review]
Checked out, and all seems to be ok. Approving merge request.

**Comment by msuder** [comment]
Did code review and executed the code.  All looks good.  Approved.

**Pull request merged**
