### PR TITLE
[nasa/nos3#204] CF reintegration

### LINKED ISSUE #162: Check for Open File in CFDP Downlink does not work
The call to CF_FileOpenCheck in cf_playback.c does not return CF_OPEN for files that are open by Data Store (DS).  This results in .ds files that are open being downlinked with a CFDP file or directory playback command.  We were able to correct this issue for our needs by changing the check in 2 places (in CF_PlaybackFileCmd and CF_PlaybackDirectoryCmd):

from:
    if (CF_FileOpenCheck(PlaybackFileCmdPtr->SrcFilename) == CF_OPEN) in CF_PlaybackFileCmd 
    if (CF_FileOpenCheck(FullSrcName) == CF_OPEN) in CF_PlaybackDirectoryCmd

to:
   if (OS_FileOpenCheck(PlaybackFileCmdPtr->SrcFilename) == OS_SUCCESS) in CF_PlaybackFileCmd 
   if (OS_FileOpenCheck(FullSrcName) == OS_SUCCESS) in CF_PlaybackDirectoryCmd

### LINKED ISSUE #204: cFS Draco CF Reintegration
On hold until https://github.com/nasa/nos3/issues/175 is completed

### PR DESCRIPTION
**Pull request by jlucas9**
Updated the CFDP engine in COSMOS to work with the draco-rc4 version of the CF application in use by NOS3.

Test runner scripts for LPT CFDP testing were added to include small and large files for class 1 and class 2.

The following merge requests must be completed prior to this one:
- [x] https://github.com/nasa-itc/CF/pull/2
- [x] https://github.com/nasa-itc/CFS_CI/pull/3
- [x] https://github.com/nasa-itc/FM/pull/1
- [x] https://github.com/nasa-itc/gsw-cosmos/pull/18

Closes #162 
Closes #204

### CODE REVIEW

**Comment by dccutrig** [comment]
Possible issue here?

Looking for another reviewer's feedback, pulled 204 and did a clean vagrant up... seems to be hanging for me in tests.

Class 1 will uplink, but error on the downlink test.

Class 2 errors on uplink for me.

image

Eventually, the fin-ack limit is reached:

image

**Comment by Donnie-Ice** [comment]
Can confirm c1 downlink error: 
image

Can also confirm c2 uplink error:
image

**Comment by jlucas9** [comment]
Added additional setup into each of the scripts to confirm radio is downlinking prior to proceeding with tests. Also added in additional cleanup of `/tmp/nos3` to `make clean-gsw` Ready for re-check!

**Review by kevincbruce — APPROVED** [review]
Ran the tests and it seems to work, so looks good!

**Review by msuder — APPROVED** [review]
Verified that CF tests worked.  Reviewed code and everything looks ok.

**Pull request merged**
