### PR TITLE
[nasa/nos3#348] FSW unit tests in CI

### PR DESCRIPTION
**Pull request by jlucas9**
Requires the following submodules to be merged prior:
* https://github.com/nasa-itc/osal/pull/6
* https://github.com/nasa-itc/SC/pull/3

### CODE REVIEW

**Comment by jlucas9** [comment]
The following works locally for me, but not in GitHub CI for some reason:
```
make debug
make config
make build-test
make test-fsw
```

**Comment by jlucas9** [comment]
@rjbrown2 and @Donnie-Ice could you assist here? I'm at a loss as to why I'm good locally but failing in CI

**Review by msuder — APPROVED** [review]

**Comment by msuder** [comment]
Reviewed code and ran tests and everything seemed ok.

**Comment by Isgaroth-the-Green** [comment]
When I ran the tests, I got two tests failing:
image
Is this acceptable/expected behavior, or should I try changing something to get them to pass?

**Review by dacarter22 — APPROVED** [review]
All tests ran successfully on my machine

**Pull request merged**
