### PR TITLE
[nasa/nos3#339] AIT Reintegration

### PR DESCRIPTION
**Pull request by cjjacks**
Re-introduce AIT into nos3

### CODE REVIEW

**Comment by cjjacks** [comment]
This PR contains the specific nos3 changes required for adding AIT as a groundstation.  The groundstation itself is composed of two submodules: 

- https://github.com/sphinxdefense/gsw-ait.git
- https://github.com/sphinxdefense/ttc-command

Which are the AIT source code and configuration and the AstroUX based UI respectively.  The AIT GSW cab be activated by setting gsw equal to `ait` in the master config file.  Once nos3 is built and launched, the UI can then be accessed at `http://localhost:80`

Please note, that both the UI and AIT sub-modules represent a minimum viable prototype and further development needs to be done to bring them up to the level of COSMOS/OpenC3.  In their current form, the AIT/AstroUX UI provides basic telemetry monitoring and commanding.  Below are some of the main outstanding issues with AIT and the UI

```
AIT

1. Some nos3 commands are not implemented because they have string arguments.  
   As far as I know, AIT does not yet support string arguments for commands.
```

```
UI

1. Limits and Alerts need to be implemented.
3. The UI needs some performance tuning as it can be sluggish at the default nos3 data rate.
4. Need to add the monitoring dashboard.
5. Session and Security upgrades.
```

The above should not have any bearing on the changes incoming to nos3.

**Review by zlynch2 — APPROVED** [review]
Tested branch, can open ait in minimal sc config. Also can send noop command. I am approving. I also agree lets make the nos3#339-AIT branch for clean up and merge.

**Review by kevincbruce — APPROVED** [review]
Followed the earlier guide. Can open AIT, monitor some telemetry, and send a command. However, at some point it did start shifting, losing connection, and I think it eventually seemed to connect with some other sattelite. So I'll approve, but I agree that more changes are needed in a separate test branch to clean up before full integration.

**Comment by jlucas9** [comment]
Thanks again for the submission @cjjacks!

**Pull request merged**
