### PR TITLE
[nasa/nos3#380] fss checkout application

### PR DESCRIPTION
**Pull request by kevincbruce**
Added checkout application for FSS to run standalone, reorganized FSS directories to match new standards, and updated ADCS to be able to read the directory with FSS's device files.

If I recall, basic test is to just see if it builds, but reviewing code to verify that I am not missing any methods and how I'm calling request data is correct would be appreciated.

Sub-PRs that must be merged first:

https://github.com/nasa-itc/generic_fss/pull/7
https://github.com/nasa-itc/generic_adcs/pull/6

### CODE REVIEW

**Comment by zlynch2** [comment]
Did you add the checkout app to make checkout? 

in order to launch standalone with make checkout?

**Comment by jlucas9** [comment]
Just pushed some changes to this. You'll still need to build the generic_fss standalone checkout manually, but the rest of the changes for testing are documented in the ./scripts/checkout.sh file and preconfigured for ease.

**Review by jlucas9 — APPROVED** [review]

**Comment by kevincbruce** [comment]
> Did you add the checkout app to make checkout?
> 
> in order to launch standalone with make checkout?

I did not yet, since I didn't know about that step (wasn't present yet in other projects, just got added). Will look at John's changes and see if that fixed, if not will push a fix. Good catch! @zlynch2

**Review by rjbrown2 — APPROVED** [review]
Looks good other than checkout application.

**Pull request merged**
