### PR TITLE
[nasa/Nos3#325 ] Equuleus upgrade

### PR DESCRIPTION
**Pull request by rjbrown2**
Must review and approve these first:

- [ ] https://github.com/nasa-itc/cFE/pull/2
- [ ] https://github.com/nasa-itc/PSP/pull/4
- [ ] https://github.com/nasa-itc/osal/pull/5

### CODE REVIEW

**Review by zlynch2 — APPROVED** [review]
Pulled 325, updated submodules, then pulled nos3#325 branch for psp, osal, and cfe. 
I checked out in minimal and full s/c config. Things seem to be in order and everything builds ok. Approving.

**Comment by rjbrown2** [comment]
Mark found that the nos3-mission.xml is still in sc-minimal-config.xml --- Change this back to sc-full-config.xml

**Comment by msuder** [comment]
Pulled the 325 branch.  Updated submodules.  Ran minimal and full scenarios and things worked as planned.  Approved for merge.

**Comment by jlucas9** [comment]
Looks good to me! Put in a minor hotfix to resolve 42 IPC conflicts with the thruster and IMU which seem to be from the `dev` branch and not this work in order to fully verify 42 launching and sun pointing. Confirmed CFDP class 2 also appears to work via test runner.

**Review by jlucas9 — APPROVED** [review]

**Review by msuder — COMMENTED** [review]
Approved

**Pull request merged**
