### PR TITLE
[nasa/nos3#269] Local COSMOS 

### PR DESCRIPTION
**Pull request by jlucas9**
In order to support local COSMOS, needed to update to use ./COMPONENTS folder.

Requires the following submodule to be merged first:
* https://github.com/nasa-itc/gsw-cosmos/pull/19

Closes:
* https://github.com/nasa/nos3/issues/275
* https://github.com/nasa/nos3/issues/269
* https://github.com/nasa/nos3/issues/250

### CODE REVIEW

**Review by kevincbruce — APPROVED** [review]
Looks good to me!

**Comment by Isgaroth-the-Green** [comment]
I am having some difficulty getting this branch to run; something strange appears to be going on with the nos_time_driver. It might just be my machine, though. Also, are docker_cryptolib_build.sh and docker_checkout.sh supposed to be non-exectuable? They are when I try running this (and also dev, incidentally), and have to be changed before I can get "make" to run without error.

**Comment by jlucas9** [comment]
> I am having some difficulty getting this branch to run; something strange appears to be going on with the nos_time_driver. It might just be my machine, though. Also, are docker_cryptolib_build.sh and docker_checkout.sh supposed to be non-exectuable? They are when I try running this (and also dev, incidentally), and have to be changed before I can get "make" to run without error.

Is this from a fresh clone? Could you try a repo_rinse.sh and see if that resolves it for you or recloning? Also could you `make real-clean; make prep` again?
* https://gist.github.com/nicktoumpelis/11214362
* git clone https://github.com/nasa/nos3.git -b nos3#269

**Comment by Isgaroth-the-Green** [comment]
It looks like I may have somehow pulled an earlier commit; when I ran git pull everything got back to a functional state.

**Comment by jlucas9** [comment]
> It looks like I may have somehow pulled an earlier commit; when I ran git pull everything got back to a functional state. COSMOS is not wanting to go past the introductory screen, though; when I accept the terms and conditions it goes away and nothing takes its place.

Did you get the latest submodule update to COSMOS? I have commit [d72c403]

**Review by Isgaroth-the-Green — APPROVED** [review]
Things now seem to all be working for me.

**Comment by szemerick** [comment]
I did a completely fresh roll.  All checks out.  I verified Igniter, verifier COSMOS works, tested RW torque, the tested SunSafe pointing multiple times. Performance is good using default configuration.

**Review by szemerick — APPROVED** [review]
All checked out. Performed multiple SunSafe modes. Tested COSMOS and Igniter.

**Pull request merged**
