### PR TITLE
[nasa/nos3#202] TC commanding and SSP telemetry

### PR DESCRIPTION
**Pull request by jlucas9**
Enable CryptoLib for CI TC side only, leave TO SPP packets.

VCID 1 = Clear mode (default)
VCID 4 = Authenticated Encryption

Requires the following submodules reviewed and merged prior to closure:
* https://github.com/nasa/CryptoLib/pull/236
* https://github.com/nasa-itc/CFS_IO_LIB/pull/2
* https://github.com/nasa-itc/CFS_TO/pull/4

### CODE REVIEW

**Review by rjbrown2 — APPROVED** [review]
Builds, fine.
Can see the change in clear vs auth enc when changing vcid from 0 to 4.

Comment says VCID1 (But it defaults to 0)  ... Just as an fyi (Special case?)

Otherwise, looks good.

**Comment by rjbrown2** [comment]
Should also note, that this was just tested with NOOP commands.  Enable TO spams and crashes the terminal.

**Review by msuder — APPROVED** [review]
Tested and reviewed code.

**Review by Donnie-Ice — APPROVED** [review]
Everything seems to be working now

**Comment by jlucas9** [comment]
image

**Pull request merged**
