### PR TITLE
[nasa/nos3#227] Propulsion

### PR DESCRIPTION
**Pull request by msuder**
Pull request to add in new generic_thruster component to NOS3 dev branch.

### CODE REVIEW

**Comment by msuder** [comment]
To test:
1.  Run NOS3
2. Send command to enable thrusters
3. Send command(s) to set thruster (1 to 4) to a percentage of full thrust
4. Observe the spacecraft reacts and rotates and/or translates

**Comment by matt11matthew** [comment]
Question relating to thrusters, are they supposed to be used to increase velocity or only used for visualization?

**Comment by msuder** [comment]
The thrusters can be used to linearly accelerate and/or rotationally accelerate the spacecraft.

**Review by Isgaroth-the-Green — APPROVED** [review]
Everything looks like it works; I did not have any trouble with running it, and it does (as far as I can tell) what it is supposed to.

**Review by jlucas9 — APPROVED** [review]

**Review by jlucas9 — APPROVED** [review]

**Pull request merged**
