### PR TITLE
[nasa/nos3#176] Basic unit tests

### PR DESCRIPTION
**Pull request by jlucas9**
Added ability to run unit tests in the sample app. Requires the following pull requests to be completed first:
* https://github.com/nasa-itc/sample/pull/14
* https://github.com/nasa-itc/hwlib/pull/8
* https://github.com/nasa-itc/osal/pull/4
* https://github.com/nasa-itc/DS/pull/2
* https://github.com/nasa-itc/SC/pull/2

### CODE REVIEW

**Comment by jlucas9** [comment]
To test this I did the following:
```
cd ~/Downloads
git clone https://github.com/nasa/nos3.git
cd nos3
git checkout nos3#176-unit-tests
git submodule update --init --recursive
make real-clean
make prep
make debug
make clean config build-test test-fsw
```
Confirmed tests passed manually at the end. Unfortunately, some tests may fail depending on the resources in your environment.

**Review by Isgaroth-the-Green — APPROVED** [review]
When I ran with a NOS3 virtual machine, things appear to all work; it has errors and failed tests when running on just a regular machine, though.

**Comment by jlucas9** [comment]
> When I ran with a NOS3 virtual machine, things appear to all work; it has errors and failed tests when running on just a regular machine, though.

Was able to replicate. Simply running `make test-fsw` again has it passing which is fun. Thinking we approve this for new and create a new issue to resolve this.

**Review by zlynch2 — COMMENTED** [review]
When running 1 test fails out of 150.  Seems to mostly work, I may be missing something small. 

image

**Comment by dccutrig** [comment]
My comment is similar. First time two tests failed, reran and one test failed.

**Review by Donnie-Ice — APPROVED** [review]
All tests passed for me

**Pull request merged**
