### PR TITLE
[nasa/nos3#267] fsw/gsw on separate machines

### PR DESCRIPTION
**Pull request by Isgaroth-the-Green**
This should be fully functional; testing will require either two actual computers or two VMs. How to run should be fairly simple - after making everything as normal (make prep, make config, make) one must run `make prep-gsw` on the computer which will run the ground software. Then, on the satellite computer, run `make prep-sat` and then the `docker swarm join` command which is output by `make prep-gsw`. 

Once the two computers have been thus connected together, merely run `make start-gsw` on the gsw computer and `make start-sat` on the satellite computer (running `make start-gsw` first). COSMOS should come up on the gsw computer, 42 and the satellite terminals on the satellite computer, and commands can then be sent between them as though they were on the same computer.

### CODE REVIEW

**Comment by msuder** [comment]
I tested this functionality on two VMs.  I was able to run GSW on one VM and FSW on another VM.  I was able to send commands from GSW to FSW and was able to receive telemetry from FSW to GSW.  I tested various NOOP commands as well as several thruster commands.  I looked at several packets of telemetry from various apps.

**Review by msuder — APPROVED** [review]
See my summary comment on testing I performed.  I approve this pull request.

**Comment by zlynch2** [comment]
Having trouble with eth1. Not connecting Working through connection issues. Couple notes:

1.  Create Steps to make Nat network in virtual box in nos3 docs
2. The real-clean script needs to remove docker swarm node (docker swarm leave --force)
3. May want to consider creating a hardcoded ethernet name when vagrant up a new vm so that ethernet definitions are the same
4.  If we dont want to do number 3, then maybe instructions on how to change prep-gsw and pre-sat ethernet names

**Comment by zlynch2** [comment]
Fixed the above comment by configuring my ethernet in my vms see below: I changed the 01.yaml files under /etc/netplan/ and ran **sudo netplan apply** after saving the changes and exiting.

GSW VM:
image

Satellite VM:
image

**Comment by zlynch2** [comment]
Tested cfs noop and worked fine after network config fixe. 

I noticed cosmos sometimes doesn't launch on the gsw vm. To get it to launch again I make clean and make. Also if you make stop on the sat VM side be sure to make stop on the GSW VM side too, then you can relaunch gsw and sat vm.

I am approving as I see it works as expected after configuring networks correctly.

**Review by zlynch2 — APPROVED** [review]
Approving feature.

**Comment by kevincbruce** [comment]
Going to try this now probably. Will try in VMs first, though if you want a separate machine test, have a raspberry pi that I might be able to test on down the line.

**Review by dacarter22 — APPROVED** [review]
Still encountered eth1 error and had to manually edit yaml files, otherwise works correctly.

**Pull request merged**
